### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by nbosc** [assefamaru/cellosaurus-api#1]
Hi! Is the API currently broken? I get the error that the server cannot be found.

**Comment by assefamaru** [comment]
Hi! The API is currently being reimplemented in Go, and the domain listed in the repository will only be available once the reimplementation is complete. The previous version of the API, however, which was implemented in Ruby, is still deployed and fully functional at the following domain http://cellosaurus.pharmacodb.com/v1/cell_lines/{id}

You can replace `{id}` with either an `identifier`, `accession id` or a `synonym name` in order to find a cell line. For example, to lookup the cell line with identifier `22rv1`, you can make request to:

```
(using accession): http://cellosaurus.pharmacodb.com/v1/cell_lines/CVCL_1045
(using identifier): http://cellosaurus.pharmacodb.com/v1/cell_lines/22rv1
(using its synonym): http://cellosaurus.pharmacodb.com/v1/cell_lines/CWR22R
```

The app is on a free tier plan on heroku, so there is a bit of a lag when making the first request. Once the API reimplementation is completed (in the coming two weeks), it will be deployed to better servers for faster performance, and the domain you had been trying will be available then. For now, I've updated both the README and description so that only working heroku version is listed as domain. Let me know if you have any other questions.

**Comment by nbosc** [comment]
Hi,
Thank you, it works.
